const allowedStepIds = new Set([
  "intro",
  "setup-check",
  "publish-starter-site",
  "analyse-brief",
  "ai-plan-mode",
  "requirements",
  "ux-ci-direction",
  "build-with-ai",
  "clean-up-test",
  "founder-judging"
]);

const answerFields = [
  "whatIChanged",
  "whyIChangedIt",
  "visitorExperienceImprovement",
  "seoOrClarityImprovement",
  "howIUsedAI",
  "whatToImproveNext"
];

const blogPosts = [
  {
    id: "digital-fatigue-marketing",
    title: "Digital Fatigue: Marketing for Attention Without Burning Users Out",
    excerpt: "Practical ways to keep engagement high without overwhelming users with constant notifications and content noise.",
    content: "The school app buzzes. I rush to check if there is breaking news about my son's class... nope. Just a very urgent reminder that his library books need to come back.\n\nAdd a few more from news alerts, a couple of messages from family in 4 different time zones, plus friends sending memes I just have to watch, and this is all before work starts. And just when I think I have earned that little dopamine hit, I get served an ad telling me that buying a collapsible play tent will make me the fun parent.\n\nOur brains were not designed for this kind of juggling. Every ping, pop-up, and just one more episode moment piles onto our mental load. Psychologists call it cognitive overload: when our working memory gets stretched past its limit.\n\nNo wonder digital fatigue feels so real. According to the latest 2025 global report by Backlinko (sourced from DataReportal), adults aged 16 to 64 now spend an average of 6 hours and 38 minutes a day on screens across devices. That is nearly half of our waking hours.\n\nGood marketing is about earning attention, not hijacking it. The sweet spot is lightweight delight: content and campaigns that spark joy, offer clarity and feel human.",
    category: "Marketing",
    tags: ["Marketing", "Engagement", "Strategy"],
    author: "Zoi Liddle",
    publishedDate: "2025-10-31",
    url: "https://www.fusedigital.io/digital-fatigue-marketing-for-attention-without-burning-users-out/",
    imageUrl: "https://www.fusedigital.io/wp-content/uploads/2025/10/LinkedIn-Marketing-Post-800x450.png"
  },
  {
    id: "analyst-storyteller",
    title: "The Analyst as Storyteller: Turning Data Into Business Narratives",
    excerpt: "How to translate raw numbers into insights teams can act on with confidence.",
    content: "We are swimming in data. Our websites, apps, social media and even the watches on our wrists are feeding us numbers daily. But data in isolation is unhelpful, and too much is as bad as too little. We need to know what to focus on and how it can help us.\n\nStorytellers have long been the translators of the human world, taking complex ideas and relationships and making meaning out of them. Give someone a list of numbers and they will quickly discard it but give them a story and it will stay with them.\n\nHistorically, website analysts provided static reports of bounce rates, session durations and conversions and left stakeholders to decipher their significance. Now, leading organisations champion their ability to turn metrics into stories that contextualise the customer journey and give actionable insights.\n\nAs Stephen Few says: Numbers have an important story to tell. They rely on you to give them a clear and convincing voice.\n\nThe analyst is no longer just a gatekeeper of reports but a catalyst for business change, shaping strategy with narratives that energise teams and clarify the customer experience.",
    category: "GA",
    tags: ["Analytics", "GA", "Insights"],
    author: "Marc Schwartz",
    publishedDate: "2025-07-31",
    url: "https://www.fusedigital.io/the-analyst-as-storyteller-turning-data-into-business-narratives/",
    imageUrl: "https://www.fusedigital.io/wp-content/uploads/2025/07/WhatsApp-Image-2025-07-30-at-15.39.14_7f176656-400x225.jpg"
  },
  {
    id: "answer-engines-seo",
    title: "The Age of Answer Engines: Is SEO Dead?",
    excerpt: "Search behavior is evolving. Learn how SEO strategy adapts in an answer-engine-first landscape.",
    content: "Search engine optimisation has long been the cornerstone of being visible online. But as user behaviour shifts and search engines evolve, the rules of the game are changing. In a world where immediate answers to questions are becoming the norm, brands must rethink their strategies to remain visible and relevant.\n\nNo-click searches occur when users find the answer to their query directly on the search results page, without clicking through to any website. Google is moving AI-first, and the traditional model of driving website visits through search is under significant pressure.\n\nAnswer engines represent a fundamental shift. They aim to deliver a single, precise answer generated by AI. This approach prioritises speed and convenience, minimising the need for users to visit external sites.\n\nThe truth is that SEO and AEO are far more similar than they are different. High-quality, relevant and up-to-date content backed up by research is the golden thread that ties SEO and AEO together.\n\nThe combination of search engines and answer engines is not just a passing trend; it is the future of how brands will be found online.",
    category: "SEO",
    tags: ["SEO", "Search", "AI"],
    author: "Marc Schwartz",
    publishedDate: "2025-07-03",
    url: "https://www.fusedigital.io/the-age-of-answer-engines-is-seo-dead/",
    imageUrl: "https://www.fusedigital.io/wp-content/uploads/2025/07/LinkedIn-SEO-Post-400x225.png"
  },
  {
    id: "brave-building-trust-ux",
    title: "How To Brave Building Trust in UX",
    excerpt: "A practical view of trust-building as a UX outcome, not just a design artifact.",
    content: "We often think of UX in terms of its outputs; the wireframes, designs and workflows that are part of any digital project. Those are vitally important, but what is their purpose? What is user experience really about?\n\nThere is a common thread between Nielsen Norman Group and Brene Brown: the belief that trust is essential to human interaction. Jakob Nielsen says trust is a long-term proposition that builds slowly as people use a site, get good results, and do not feel let down or cheated.\n\nBoundaries in UX means respecting limits: clear opt-outs, obvious close buttons, and not screaming for attention with notifications. Reliability means doing what you say you will do through consistent, dependable interactions.\n\nAccountability is how you handle mistakes. Oops, our bad. Here is what happened and here is how to get back on track is better than a cryptic error code.\n\nBy consciously weaving BRAVING into your user experience, you move beyond mere function. You start building trust.",
    category: "User Experience",
    tags: ["UX", "Trust", "Design"],
    author: "Sarah Didcott",
    publishedDate: "2025-05-15",
    url: "https://www.fusedigital.io/how-to-brave-building-trust-in-ux/",
    imageUrl: "https://www.fusedigital.io/wp-content/uploads/2025/05/LinkedIn-UX-Post-400x225.png"
  },
  {
    id: "content-management-foundation",
    title: "Constructing Digital Empires: The Foundation of Effective Content Management",
    excerpt: "Why content structure and governance are critical for scalable digital growth.",
    content: "In today's ever-evolving digital age, the foundation of a successful business relies heavily upon its ability to manage content effectively. Just as constructing a house without the proper tools or materials will inevitably lead to structural flaws and eventual failure, ineffective content management will cause your digital strategy to falter.\n\nEffective content management starts with setting clear business objectives, like boosting brand visibility and engagement, attracting new leads, or improving customer retention. Once these goals are established, they can seamlessly integrate into your content strategy.\n\nA clear content strategy is your blueprint for conquering all content-related activities. It includes audience personas, strategic planning for content types, assigning purpose to each asset, keyword research, and release scheduling.\n\nThe continuous analysis and optimisation of your content are key to enhancing performance, staying ahead of competitors, and keeping your brand relevant.\n\nBy mastering these key pillars, you can build a digital empire that stands tall and firm and excels in the competitive online landscape.",
    category: "Content Management",
    tags: ["CMS", "Content", "Operations"],
    author: "Anel Niemand",
    publishedDate: "2024-10-16",
    url: "https://www.fusedigital.io/constructing-digital-empires-the-foundation-of-effective-content-management/",
    imageUrl: "https://www.fusedigital.io/wp-content/uploads/2024/10/Fuse-Digital-Content_Management-400x225.png"
  },
  {
    id: "semantic-seo",
    title: "Beyond Keywords: The Power of Semantic SEO",
    excerpt: "Move from isolated keywords to topical authority and entity-based optimisation.",
    content: "The SEO landscape constantly evolves, demanding a deeper understanding of how search engines decipher meaning. With the rise of Large Language Models that break down text into tokens of meaning, search engines are becoming exponentially smarter at deciphering user intent and the nuances of language.\n\nLanguage is essentially a giant web of interconnected ideas. With advancements like Hummingbird, RankBrain, and BERT, search engines use this semantic web to understand the context of your content, going beyond individual keywords and looking at overall meaning and relevance.\n\nUnderstanding the what is only half the battle. Google also strives to understand the why behind every search. Search intent is the reason people search for specific terms, and that intent directly affects the search results returned.\n\nBy aligning your content with user intent and leveraging semantic relationships, you paint a clearer picture for search engines. You are not just using the right words, you are demonstrating deep understanding and providing genuinely valuable information that answers the query comprehensively.",
    category: "SEO",
    tags: ["SEO", "Semantic Search", "Content"],
    author: "Charlie Human",
    publishedDate: "2024-08-21",
    url: "https://www.fusedigital.io/beyond-keywords-the-power-of-semantic-seo/",
    imageUrl: "https://www.fusedigital.io/wp-content/uploads/2024/09/SEO-Blog-Post-400x225.png"
  },
  {
    id: "understanding-ux-methodology",
    title: "Understanding UX: It's a methodology, not just a product",
    excerpt: "Reframing UX as an ongoing way of working rather than a once-off design output.",
    content: "The rapidly evolving digital landscape has embraced user experience (UX) as a buzzword. People often use it interchangeably with terms like design or product, but UX is more than just crafting wireframes. It is a methodology encompassing principles, processes and practices that create tangible products like websites, apps, or interfaces.\n\nUX research goes deeper than user preferences and behaviour. It defines problem statements, business contexts, and the broader scope of user needs. When teams jump into wireframes without first exploring the problem space, understanding the business domain, or empathising with end users, the final product suffers.\n\nUsability testing is essential. Without thorough testing, teams may overlook confusing navigation, slow loading times, or inaccessible features. This leads to frustration and abandonment.\n\nUX extends beyond reducing clicks or moving buttons. It encompasses the entire user journey. When different parts of a product or service are designed in isolation, they do not create a cohesive journey for the user.",
    category: "User Experience",
    tags: ["UX", "Methodology", "Product"],
    author: "Candice Dingle",
    publishedDate: "2024-08-08",
    url: "https://www.fusedigital.io/understanding-ux",
    imageUrl: "https://www.fusedigital.io/wp-content/uploads/2024/09/UX-Post-SEO.png"
  },
  {
    id: "discipline-roi",
    title: "The Compounding Return on Investment in Discipline",
    excerpt: "How disciplined operating rhythms compound into stronger long-term performance.",
    content: "What can I say? I am a late bloomer. I have only recently learned that the elementary character trait required in our quest to create value in our lives and strive towards our goals is discipline.\n\nAlthough it is sometimes viewed as a stiff and cold concept, there is an undeniable correlation between discipline and success. Through discipline, we cultivate consistency, create routines, form habits, and conquer our challenges to bring our dreams to fruition.\n\nMotivation and discipline are interconnected but different. Motivation is the initial spark that ignites desire. Discipline is the unwavering commitment to the goal regardless of conditions or feelings.\n\nLike investing money in a bank, discipline comes with compound interest that multiplies its benefits over time. Consistency leads to routines, routines create habits, and habits become second nature.\n\nThe ROI on discipline is not measured in monetary terms. It is measured through personal growth, goal accomplishment, character building, and a fulfilled life.",
    category: "Leadership",
    tags: ["Leadership", "Performance", "Culture"],
    author: "Gideon de Swardt",
    publishedDate: "2023-07-13",
    url: "https://www.fusedigital.io/blog/the-compounding-return-on-investment-in-discipline/",
    imageUrl: "https://www.fusedigital.io/wp-content/uploads/2023/07/fuse-digital_article_compounding-return-on-investment-in-discipline-400x267.jpg"
  },
  {
    id: "collaboration-tools-double-edge",
    title: "The double edge sword of collaboration tools",
    excerpt: "Collaboration platforms can increase alignment or create overload depending on team norms.",
    content: "The rise of collaboration tools like Zoom, Teams, and Slack has positively and negatively impacted our productivity. On the one hand, these tools have made communication and teamwork more effortless and accessible than ever before. On the other hand, constant interruptions and lack of priority clarity can decrease focus and create an overwhelming feeling of never achieving anything.\n\nAs per recent polls we ran on LinkedIn, the average time spent in meetings has doubled, and in some cases tripled, since 2020. The abundance of meetings and constant interruptions can lead to a feeling of never being able to complete anything and being constantly overwhelmed.\n\nTo mitigate this, we created a company-wide communication guideline. Internal Slack is asynchronous. The expectation is that when something is posted on Slack, there is no immediate requirement for a reaction, especially outside business hours.\n\nEmails are used for formal communication with clients and vendors and are sent during business hours. Internal and external group WhatsApp or Signal should only be used when immediate action is required.\n\nBy creating clear expectations and fostering respectful communication, we can harness these tools' power to improve work processes and deliver the highest business value first.",
    category: "Technology",
    tags: ["Technology", "Collaboration", "Productivity"],
    author: "Gideon de Swardt",
    publishedDate: "2023-03-17",
    url: "https://www.fusedigital.io/blog/the-double-edge-sword-of-collaboration-tools/",
    imageUrl: "https://www.fusedigital.io/wp-content/uploads/2023/03/fuse-digital_article_collaboration-tools-400x267.jpg"
  }
];

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") {
      return new Response(null, {
        status: 204,
        headers: buildCorsHeaders(request, env)
      });
    }

    const url = new URL(request.url);

    if (url.pathname === "/api/health" && request.method === "GET") {
      return jsonResponse({ ok: true }, 200, request, env);
    }

    if (url.pathname === "/api/progress" && request.method === "GET") {
      const participants = await listParticipants(env);
      return jsonResponse({ participants }, 200, request, env);
    }

    if (url.pathname === "/api/progress" && request.method === "POST") {
      try {
        const payload = await request.json();
        const validatedPayload = validatePayload(payload);
        await upsertParticipant(env, validatedPayload);
        const participants = await listParticipants(env);
        return jsonResponse({ participants }, 200, request, env);
      } catch (error) {
        return jsonResponse({ error: error.message || "Could not save progress." }, 400, request, env);
      }
    }

    if (url.pathname === "/api/blog" && request.method === "GET") {
      const posts = listBlogPosts();
      return jsonResponse({ posts }, 200, request, env);
    }

    const blogPostMatch = url.pathname.match(/^\/api\/blog\/([^/]+)$/);
    if (blogPostMatch && request.method === "GET") {
      const postId = decodeURIComponent(blogPostMatch[1]);
      const post = getBlogPostById(postId);

      if (!post) {
        return jsonResponse({ error: "Blog post not found." }, 404, request, env);
      }

      return jsonResponse({ post }, 200, request, env);
    }

    return jsonResponse({ error: "Not found." }, 404, request, env);
  }
};

function validatePayload(payload) {
  if (!payload || typeof payload !== "object") {
    throw new Error("Payload must be an object.");
  }

  const username = normaliseUsername(payload.username);
  const repoUrl = validateOptionalUrl(payload.repoUrl, "repoUrl");
  const liveUrl = validateOptionalUrl(payload.liveUrl, "liveUrl");
  const completedSteps = Array.isArray(payload.completedSteps) ? payload.completedSteps : [];
  const cleanCompletedSteps = [...new Set(completedSteps)].filter(stepId => allowedStepIds.has(stepId));
  const hasAnswers = Object.prototype.hasOwnProperty.call(payload, "answers");
  const answers = hasAnswers ? validateAnswers(payload.answers) : null;

  return {
    username,
    repoUrl,
    liveUrl,
    completedSteps: cleanCompletedSteps,
    answers,
    hasAnswers
  };
}

function validateAnswers(rawAnswers) {
  if (!rawAnswers || typeof rawAnswers !== "object") {
    return buildEmptyAnswers();
  }

  const answers = {};

  answerFields.forEach(field => {
    const value = rawAnswers[field];

    if (typeof value !== "string") {
      answers[field] = "";
      return;
    }

    answers[field] = value.trim().slice(0, 4000);
  });

  return answers;
}

function buildEmptyAnswers() {
  return {
    whatIChanged: "",
    whyIChangedIt: "",
    visitorExperienceImprovement: "",
    seoOrClarityImprovement: "",
    howIUsedAI: "",
    whatToImproveNext: ""
  };
}

function normaliseUsername(username) {
  if (typeof username !== "string") {
    throw new Error("Username is required.");
  }

  const clean = username.trim().toLowerCase().replace(/^@/, "");

  if (!clean) {
    throw new Error("Username is required.");
  }

  if (!/^[a-z0-9-]+$/.test(clean)) {
    throw new Error("Username may only contain letters, numbers, and hyphens.");
  }

  return clean;
}

function validateOptionalUrl(value, fieldName) {
  if (!value) {
    return "";
  }

  if (typeof value !== "string") {
    throw new Error(`${fieldName} must be a string.`);
  }

  const clean = value.trim();

  if (!clean) {
    return "";
  }

  if (!/^https?:\/\//i.test(clean)) {
    throw new Error(`${fieldName} must start with http:// or https://`);
  }

  return clean;
}

async function upsertParticipant(env, payload) {
  const now = new Date().toISOString();
  const completedStepsJson = JSON.stringify(payload.completedSteps);

  await env.DB.prepare(
    `
      INSERT INTO participants (username, repo_url, live_url, completed_steps_json, created_at, updated_at)
      VALUES (?1, ?2, ?3, ?4, ?5, ?6)
      ON CONFLICT(username) DO UPDATE SET
        repo_url = excluded.repo_url,
        live_url = excluded.live_url,
        completed_steps_json = excluded.completed_steps_json,
        updated_at = excluded.updated_at
    `
  )
    .bind(payload.username, payload.repoUrl, payload.liveUrl, completedStepsJson, now, now)
    .run();

  if (payload.hasAnswers) {
    const answersJson = JSON.stringify(payload.answers || buildEmptyAnswers());

    await env.DB.prepare(
      `
        INSERT INTO participant_answers (username, answers_json, created_at, updated_at)
        VALUES (?1, ?2, ?3, ?4)
        ON CONFLICT(username) DO UPDATE SET
          answers_json = excluded.answers_json,
          updated_at = excluded.updated_at
      `
    )
      .bind(payload.username, answersJson, now, now)
      .run();
  }
}

async function listParticipants(env) {
  const result = await env.DB.prepare(
    `
      SELECT p.username, p.repo_url, p.live_url, p.completed_steps_json, p.created_at, p.updated_at, a.answers_json
      FROM participants p
      LEFT JOIN participant_answers a ON a.username = p.username
    `
  ).all();

  const rows = Array.isArray(result.results) ? result.results : [];

  const participants = rows.map(row => ({
    username: row.username,
    repoUrl: row.repo_url,
    liveUrl: row.live_url,
    completedSteps: parseCompletedSteps(row.completed_steps_json),
    answers: parseAnswers(row.answers_json),
    createdAt: row.created_at,
    updatedAt: row.updated_at
  }));

  participants.sort((a, b) => {
    const completedDiff = b.completedSteps.length - a.completedSteps.length;
    if (completedDiff !== 0) {
      return completedDiff;
    }

    const updatedAtDiff = new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime();
    if (updatedAtDiff !== 0) {
      return updatedAtDiff;
    }

    return a.username.localeCompare(b.username);
  });

  return participants;
}

function parseCompletedSteps(rawValue) {
  try {
    const parsed = JSON.parse(rawValue);
    return Array.isArray(parsed) ? parsed.filter(stepId => allowedStepIds.has(stepId)) : [];
  } catch {
    return [];
  }
}

function jsonResponse(body, status, request, env) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Cache-Control": "no-store",
      ...buildCorsHeaders(request, env)
    }
  });
}

function buildCorsHeaders(request, env) {
  const origin = request.headers.get("Origin");
  const allowedOrigin = normaliseAllowedOrigin(env.ALLOWED_ORIGIN);

  return {
    "Access-Control-Allow-Origin": origin && allowedOrigin !== "*" ? allowedOrigin : allowedOrigin,
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    Vary: "Origin"
  };
}

function normaliseAllowedOrigin(rawValue) {
  if (!rawValue || rawValue.includes("REPLACE")) {
    return "*";
  }

  const value = String(rawValue).trim();

  if (!value) {
    return "*";
  }

  try {
    const parsed = new URL(value);
    return parsed.origin;
  } catch {
    return value.replace(/\/+$/, "");
  }
}

function parseAnswers(rawValue) {
  if (!rawValue) {
    return buildEmptyAnswers();
  }

  try {
    return validateAnswers(JSON.parse(rawValue));
  } catch {
    return buildEmptyAnswers();
  }
}

function listBlogPosts() {
  return [...blogPosts]
    .sort((a, b) => b.publishedDate.localeCompare(a.publishedDate));
}

function getBlogPostById(postId) {
  return blogPosts.find(post => post.id === postId) || null;
}